; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:base_native]
platform = native

[env:bit_manipulation]
extends = env:base_native
build_src_filter = -<*> +<06_bit_manipulation/>

[env:struct]
extends = env:base_native
build_src_filter = -<*> +<07_struct/> 

[env:function]
extends = env:base_native
build_src_filter = -<*> +<08_function/> 
